apiVersion: v1
kind: ServiceAccount
metadata:
  name: catalog
  namespace: shopcloud
  annotations:
    eks.amazonaws.com/role-arn: CATALOG_IRSA_ROLE_ARN
  labels:
    app: catalog
automountServiceAccountToken: true
