apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopcloud-admin
  namespace: shopcloud
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/certificate-arn: REPLACE_ACM_ARN
    alb.ingress.kubernetes.io/inbound-cidrs: "10.0.0.0/8"
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/group.name: shopcloud-internal
spec:
  rules:
    - http:
        paths:
          - path: /api/v1/admin
            pathType: Prefix
            backend:
              service:
                name: admin
                port:
                  number: 80
