apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: shopcloud
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: shopcloud
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: shopcloud
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: shopcloud
spec:
  replicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: shopcloud
spec:
  replicas: 1
