name: PR Checks

on:
  pull_request:
    branches: [develop, main]

jobs:
  lint-terraform:
    name: Terraform Lint & Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.0"
      - name: Terraform Format Check
        run: terraform fmt -check -recursive terraform/
      - name: Validate Dev
        working-directory: terraform/environments/dev
        run: |
          terraform init -backend=false
          terraform validate
      - name: Validate Prod
        working-directory: terraform/environments/prod
        run: |
          terraform init -backend=false
          terraform validate

  lint-k8s:
    name: Kubernetes Manifest Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install kubeconform
        run: |
          curl -sL https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
          sudo mv kubeconform /usr/local/bin/
      - name: Validate K8s manifests
        run: |
          kubeconform -strict -summary -output json k8s/base/

  dependency-audit:
    name: Dependency Audit (${{ matrix.service }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [catalog, cart, checkout, auth, admin]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm audit --audit-level=high
        working-directory: services/${{ matrix.service }}
